services:
  builder:
    platform: linux/amd64
    build:
      args:
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        GIT_USER_NAME: ${GIT_USER_NAME}
      context: .
      dockerfile: ./Dockerfile
    container_name: builder
    env_file:
      - .env
    volumes:
      - source:/home/user/workdir
    working_dir: /home/user/workdir/source
    stdin_open: true
    tty: true
    command: sleep infinity
    restart: unless-stopped
    privileged: true

volumes:
  source:
