services:
  env:
    platform: linux/amd64
    build:
      args:
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        GIT_USER_NAME: ${GIT_USER_NAME}
      context: .
      dockerfile: ./Dockerfile
    container_name: env
    env_file:
      - .env
    volumes:
      - volume:/home/ubuntu/workdir
    user: "ubuntu"
    working_dir: /home/ubuntu/workdir/source
    stdin_open: true
    tty: true
    command: sleep infinity
    restart: unless-stopped
    privileged: true

volumes:
  volume:
    driver: local
    driver_opts:
      type: none
      device: ./volume
      o: bind
