services:
  env:
    platform: linux/amd64
    build:
      args:
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        GIT_USER_NAME: ${GIT_USER_NAME}
      context: .
      dockerfile: ./Dockerfile
    container_name: env
    env_file:
      - .env
    volumes:
      - volume:/home/user/workdir
    working_dir: /home/user/workdir/source
    stdin_open: true
    tty: true
    command: sleep infinity
    restart: unless-stopped
    privileged: true

volumes:
  volume:
    driver: local
# Use bind mount only with case-sensitive file systems
#    driver_opts:
#      type: none
#      device: ./volume
#      o: bind
